name: Create PDF

on: [push]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: uwthesis.tex
          latexmk_use_xelatex: true
      
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: uwthesis.pdf
      
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.sha }}
          files: uwthesis.pdf
          make_latest: true